fixed shell alias

diff --git a/config/shell/funcs b/config/shell/funcs
--- a/config/shell/funcs
+++ b/config/shell/funcs
@@ -1,34 +1,4 @@
-# Function to source files if they exist
-function zsh_add_file() {
-    [ -f "$XDG_CACHE_HOME/zsh/$1" ] && source "$XDG_CACHE_HOME/zsh/$1"
-}
-
-function zsh_add_plugin() {
-    PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
-    if [ -d "$XDG_CACHE_HOME/zsh/plugins/$PLUGIN_NAME" ]; then
-        # For plugins
-        zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh" || \
-        zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.zsh"
-    else
-        git clone "https://github.com/$1.git" "$XDG_CACHE_HOME/zsh/plugins/$PLUGIN_NAME"
-    fi
-}
-
-function zsh_add_completion() {
-    PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
-    if [ -d "$XDG_CACHE_HOME/zsh/plugins/$PLUGIN_NAME" ]; then
-        # For completions
-		completion_file_path=$(ls $XDG_CACHE_HOME/zsh/plugins/$PLUGIN_NAME/_*)
-		fpath+="$(dirname "${completion_file_path}")"
-        zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh"
-    else
-        git clone "https://github.com/$1.git" "$XDG_CACHE_HOME/zsh/plugins/$PLUGIN_NAME"
-		fpath+=$(ls $XDG_CACHE_HOME/zsh/plugins/$PLUGIN_NAME/_*)
-        [ -f $XDG_CACHE_HOME/zsh/.zccompdump ] && $XDG_CACHE_HOME/zsh/.zccompdump
-    fi
-	completion_file="$(basename "${completion_file_path}")"
-	if [ "$2" = true ] && compinit "${completion_file:1}"
-}
+# shellcheck shell=bash source=/dev/null
 
 # Function to switch betweeen background and foreground programs
 function fg-bg() {
@@ -644,7 +614,7 @@ xname(){
 }
 
 shdl() { curl -O $(curl -s http://sci-hub.tw/"$@" | grep location.href | grep -o http.*pdf) ;}
-se() { du -a ~/bin/* ~/.config/* | awk '{print $2}' | fzf | xargs -r $EDITOR ;}
+se() { du -a ~/.local/bin/* ~/.config/* | awk '{print $2}' | fzf | xargs -r $EDITOR ;}
 vf() { fzf | xargs -r -I % $EDITOR % ;}
 
 # Return the number of processors available
@@ -1071,10 +1041,10 @@ lfcd () {
     if [ -f "$tmp" ]; then
         dir="$(cat "$tmp")"
         rm -f "$tmp" >/dev/null
-        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
+      x [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
     fi
 }
-bindkey -s '^o' 'lfcd\n'
+#bind -s '^o' 'lfcd\n'
 
 # grep for processes
 function pg { pgrep -fa "$1" | grep -E --color "$1"; }
@@ -1546,76 +1516,6 @@ dexec() {
 }
 
 
-# Extract multiple types of compressed archives
-extract() {
-	local remove_archive
-	local success
-	local extract_dir
-
-	if (( $# == 0 )); then
-		cat <<-'EOF' >&2
-			Usage: extract [-option] [file ...]
-			Options:
-			    -r, --remove    Remove archive after unpacking.
-		EOF
-	fi
-
-	remove_archive=1
-	if [[ "$1" == "-r" ]] || [[ "$1" == "--remove" ]]; then
-		remove_archive=0
-		shift
-	fi
-
-	while (( $# > 0 )); do
-		if [[ ! -f "$1" ]]; then
-			echo "extract: '$1' is not a valid file" >&2
-			shift
-			continue
-		fi
-
-		success=0
-		extract_dir="${1:t:r}"
-		case "${1:l}" in
-			(*.tar.gz|*.tgz) (( $+commands[pigz] )) && { pigz -dc "$1" | tar xv } || tar zxvf "$1" ;;
-			(*.tar.bz2|*.tbz|*.tbz2) tar xvjf "$1" ;;
-			(*.tar.xz|*.txz)
-				tar --xz --help &> /dev/null \
-				&& tar --xz -xvf "$1" \
-				|| xzcat "$1" | tar xvf - ;;
-			(*.tar.zma|*.tlz)
-				tar --lzma --help &> /dev/null \
-				&& tar --lzma -xvf "$1" \
-				|| lzcat "$1" | tar xvf - ;;
-			(*.tar) tar xvf "$1" ;;
-			(*.gz) (( $+commands[pigz] )) && pigz -d "$1" || gunzip "$1" ;;
-			(*.bz2) bunzip2 "$1" ;;
-			(*.xz) unxz "$1" ;;
-			(*.lzma) unlzma "$1" ;;
-			(*.z) uncompress "$1" ;;
-			(*.zip|*.war|*.jar|*.sublime-package|*.ipsw|*.xpi|*.apk|*.aar|*.whl) unzip "$1" -d $extract_dir ;;
-			(*.rar) unrar x -ad "$1" ;;
-			(*.7z) 7za x "$1" ;;
-			(*.deb)
-				mkdir -p "$extract_dir/control"
-				mkdir -p "$extract_dir/data"
-				cd "$extract_dir"; ar vx "../${1}" > /dev/null
-				cd control; tar xzvf ../control.tar.gz
-				cd ../data; extract ../data.tar.*
-				cd ..; rm *.tar.* debian-binary
-				cd ..
-			;;
-			(*)
-				echo "extract: '$1' cannot be extracted" >&2
-				success=1
-			;;
-		esac
-
-		(( success = $success > 0 ? $success : $? ))
-		(( $success == 0 )) && (( $remove_archive == 0 )) && rm "$1"
-		shift
-	done
-}
-
 # Kubernetes helpers
 
 # deploys a helm chart a number of times to a cluster pointed to by KUBECONFIG environment setting
@@ -1697,4 +1597,43 @@ get_lbname(){
 
 drop_awslb(){
 	aws elbv2 delete-load-balancer --load-balancer-arn "$1" # aws cli doesn't seem to support multiple arns? 
+}
+
+# Delete a given line number in the known_hosts file.
+knownrm() {
+ re='^[0-9]+$'
+ if ! [[ $1 =~ $re ]] ; then
+   echo "error: line number missing" >&2;
+ else
+   sed -i "$1d" ~/.ssh/known_hosts
+ fi
+}
+
+# Open yazi and change to currently browesed directory when exiting
+function y() {
+	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
+	yazi "$@" --cwd-file="$tmp"
+	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
+		builtin cd -- "$cwd"
+	fi
+	rm -f -- "$tmp"
+}
+
+kctx() {
+  (
+    cd ~/.kube/ || exit 1
+    # shellcheck disable=SC2012
+    KUBE=$(ls kube-* | fzf)
+    [[ -n "$KUBE" ]] && ln -sf "$KUBE" config
+  )
+}
+
+klctx() {
+    # shellcheck disable=SC1083
+    local SEARCH="${1:-$HOME/Downloads}"
+    [[ "$1" == "-" ]] && SEARCH="$HOME/.kube"
+    local KUBE=$(ls "$SEARCH" -p -t | grep -v / | fzf)
+    if [[ -n "$KUBE" ]]; then
+      export KUBECONFIG="${SEARCH%/}/$KUBE"
+    fi
 }
