Fixed formatting errors

diff --git a/local/bin/spacebot b/local/bin/spacebot
--- a/local/bin/spacebot
+++ b/local/bin/spacebot
@@ -12,10 +12,9 @@ script_url_raw=https://gitlab.com/beepmode/spacebot/-/raw/master/spacebot
 
 # Vim :set tabstop=2 shiftwidth=2 expendtab
 
-
 # VARIABLES
 # --------------------------------------------------------------------
-# Default variables used in the script. You can change the variables 
+# Default variables used in the script. You can change the variables
 # on the fly via command line options.
 
 # [$check_files] and [$no_check_files]
@@ -65,10 +64,9 @@ output_file=spacebot_$(date +"%Y%m%d%H%M")
 output_file_tmp=spacebot_tmp
 
 # [$email]
-# An array of email addresses. The script's output will be sent to 
+# An array of email addresses. The script's output will be sent to
 # these addresses.
-email=( example1@example.com example2@example.com )
-
+email=(example1@example.com example2@example.com)
 
 # GENERAL FUNCTIONS
 # --------------------------------------------------------------------
@@ -82,13 +80,14 @@ housekeeping() {
 
 # Function to join elements of an array.
 join_array() {
-  local IFS="$1"; shift ; echo "$*";
+  local IFS="$1"
+  shift
+  echo "$*"
 }
-
 
 # VALIDATION FUNCTIONS
 # --------------------------------------------------------------------
-# Function to validate $check_files and $no_check_files. We just need 
+# Function to validate $check_files and $no_check_files. We just need
 # to make sure that both aren't set to true.
 validate_check_files() {
   if [ -n "$check_files" ] && [ "$no_check_files" ]; then
@@ -100,7 +99,7 @@ validate_check_files() {
   fi
 }
 
-# Function to validate $check_dirs and $no_check_dirs. We just need 
+# Function to validate $check_dirs and $no_check_dirs. We just need
 # to make sure that both aren't set to true.
 validate_check_dirs() {
   if [ -n "$check_dirs" ] && [ "$no_check_dirs" ]; then
@@ -128,7 +127,7 @@ validate_file_size() {
     exit 1
   fi
 
-  # $size may include a tailing character defining the unit (as per 
+  # $size may include a tailing character defining the unit (as per
   # the `find` man page). If no unit is specified $size_init is used.
   if [[ $file_size =~ ([0-9])$ ]]; then
     file_size=${file_size}${file_size_unit}
@@ -140,19 +139,19 @@ validate_file_size() {
 
 # Function to validate $file_sort.
 validate_file_sort() {
-  case "$file_sort" in 
-    size)
-      sort_cmd() { sort -hr; }
+  case "$file_sort" in
+  size)
+    sort_cmd() { sort -hr; }
     ;;
-    date)
-      sort_cmd() { sort -rk 2; }
+  date)
+    sort_cmd() { sort -rk 2; }
     ;;
-    file|name)
-      sort_cmd() { sort -k 3; }
+  file | name)
+    sort_cmd() { sort -k 3; }
     ;;
-    *)
-      printf '%s\n' "*** Error: invalid sort order ($file_sort) ***"
-      exit 1
+  *)
+    printf '%s\n' "*** Error: invalid sort order ($file_sort) ***"
+    exit 1
     ;;
   esac
 }
@@ -192,12 +191,12 @@ validate_output() {
 # Function to validate email addresses.
 validate_email() {
 
-  # We need to validate the email addresses(es) and check if mailx 
-  # is installed. $no_mail is introduced here to keep track if we 
+  # We need to validate the email addresses(es) and check if mailx
+  # is installed. $no_mail is introduced here to keep track if we
   # can fire off an email:
   no_email=false
 
-  # Next, we check if $email has been set to 'none'. If it's not we 
+  # Next, we check if $email has been set to 'none'. If it's not we
   # crack on and validate the email addresses:
   if [ "${email[*]}" = "none" ]; then
     no_email=true
@@ -210,29 +209,28 @@ validate_email() {
     done
   else
     no_email=true
-  fi 
+  fi
 
   # Join the mail array (as mailx wants a comma-separated string):
   mail_string=$(join_array ',' "${email[@]}")
 
-  # And finally, make sure mailx is installed (we only need to 
+  # And finally, make sure mailx is installed (we only need to
   # check this if $no_email is still false):
   if [ "$no_email" = false ]; then
-    if ! command -v mailx &> /dev/null; then
+    if ! command -v mailx &>/dev/null; then
       no_email=true
       printf '%s\n' "" "*** Warning: no email will be sent as mailx is not installed.***"
     fi
   fi
 }
 
-
 # FUNCTIONS THAT PRINT STUFF
 # --------------------------------------------------------------------
 # Function to print help information
 function print_help() {
-cat <<-USAGE
+  cat <<-USAGE
 
-$script_name finds large files and/or directories. It understands the 
+$script_name finds large files and/or directories. It understands the
 following options:
 
 --check-files
@@ -251,14 +249,14 @@ Do not look for large directores.
 The directory that should be checked.
 
 --file-size=[size]
-The minimum file size. You can append units such as 'k', 'M' and 'G'. 
+The minimum file size. You can append units such as 'k', 'M' and 'G'.
 (i.e. both '100' and '100M' are valid).
 
 --file-sort=[size|date|file]
 Sort the list of large files by size, date or file.
 
 --dir-limit=[number]
-The number of large directories that should be listed when looking 
+The number of large directories that should be listed when looking
 for large directories
 
 --output-dir=[dir]
@@ -268,8 +266,8 @@ The directory where the script's output should be stored.
 The name of the output file.
 
 --email=[email@address|none]
-One or more email addresses to which the output should be send. You 
-can specify multiple addresses (use double quotes and separate the 
+One or more email addresses to which the output should be send. You
+can specify multiple addresses (use double quotes and separate the
 addresses with spaces). Use 'none' to disable the email function.
 
 --vardump
@@ -285,27 +283,27 @@ Print license information
 Print this help text
 
 USAGE
-exit 0
+  exit 0
 }
 
 # Function to print version information
 function print_version() {
-cat <<-VERSION
+  cat <<-VERSION
 $script_name $script_version ($script_date):
 URL: $script_url
 Raw: $script_url_raw
 
 VERSION
-exit 0
+  exit 0
 }
 
 # Function to print license information
 function print_license() {
-cat <<- LICENSE
+  cat <<-LICENSE
 $script_license
 
 LICENSE
-exit 0
+  exit 0
 }
 # Function to dump variables
 print_vars() {
@@ -335,44 +333,44 @@ find_files() {
   # Required functions
   validate_file_size
   validate_file_sort
-  
+
   # Print a header for the output file:
   {
-  printf '%s\n' "Files larger than $file_size in $dir"
-  printf '%s\n' "======================================================================"
-  } >> "$output"
+    printf '%s\n' "Files larger than $file_size in $dir"
+    printf '%s\n' "======================================================================"
+  } >>"$output"
 
   # Print a message for the user:
   printf '%s\n' "Finding files larger than $file_size in $dir..."
 
-  # Find the files. Virtual file systems are always excluded and stat 
-  # is used to print the size (in bytes), date (as a Unix timestamp) 
+  # Find the files. Virtual file systems are always excluded and stat
+  # is used to print the size (in bytes), date (as a Unix timestamp)
   # and name. The output is written to a temporary file.
   find "$dir" \
-  -not \( -path "/proc" -prune \) \
-  -not \( -path "/sys" -prune \) \
-  -not \( -path "/run" -prune \) \
-  -type f \
-  -size +"$file_size" \
-  -exec stat --printf='%s\t%Y\t%n\n' '{}' \+ > "$output_file_tmp"
+    -not \( -path "/proc" -prune \) \
+    -not \( -path "/sys" -prune \) \
+    -not \( -path "/run" -prune \) \
+    -type f \
+    -size +"$file_size" \
+    -exec stat --printf='%s\t%Y\t%n\n' '{}' \+ >"$output_file_tmp"
 
-  # Next, we're using awk to convert the files sizes to mebibytes and 
+  # Next, we're using awk to convert the files sizes to mebibytes and
   # the dates to something human readable.
   awk -F"\t" '
     {
       bytes = $1 /1024/1024; $2 = strftime("%Y-%m-%d", $2);
       printf "%.0f%s\t%s\t%s\n", bytes, "MB", $2, $3
      }
-    ' "$output_file_tmp" \
-  | sort_cmd \
-  | tee -a "$output"
+    ' "$output_file_tmp" |
+    sort_cmd |
+    tee -a "$output"
 
   # Print a pretty line for the output file:
-  printf '%s\n' "----------------------------------------------------------------------" "" "" >> "$output"
+  printf '%s\n' "----------------------------------------------------------------------" "" "" >>"$output"
 }
 
 # Function to find large directories
-  find_dirs() {
+find_dirs() {
 
   # Required functions:
   validate_dir_limit
@@ -380,24 +378,24 @@ find_files() {
 
   # Print a header for the output file:
   {
-  printf '%s\n' "Top $dir_limit largest directories"
-  printf '%s\n' "======================================================================"
-  } >> "$output"
+    printf '%s\n' "Top $dir_limit largest directories"
+    printf '%s\n' "======================================================================"
+  } >>"$output"
 
   # Print a message for the user:
   printf '%s\n' "" "Finding the $dir_limit largest directories in $dir..."
 
   du -ah "$dir" \
-  --exclude=/proc \
-  --exclude=/sys \
-  --exclude=/run \
-  --max-depth="$dir_depth" \
-  | sort -hr \
-  | head -"$dir_limit" \
-  | tee -a "$output"
+    --exclude=/proc \
+    --exclude=/sys \
+    --exclude=/run \
+    --max-depth="$dir_depth" |
+    sort -hr |
+    head -"$dir_limit" |
+    tee -a "$output"
 
   # Print a pretty line for the output file:
-  printf '%s\n' "----------------------------------------------------------------------" "" "" >> "$output"
+  printf '%s\n' "----------------------------------------------------------------------" "" "" >>"$output"
 }
 
 # Function to process output.
@@ -406,89 +404,87 @@ process_output() {
   # Required functions
   validate_email
 
-  # If $no_email is true we print a message to let the user know 
+  # If $no_email is true we print a message to let the user know
   # where the output is stored.
   if [ "$no_email" = true ]; then
     printf '%s\n' "" "Output is stored in $output".
     exit 0
   elif [ -s "$output" ]; then
-    if ! mailx -s "Disk usage (large files on $HOSTNAME)" "$mail_string" < "$output"; then
+    if ! mailx -s "Disk usage (large files on $HOSTNAME)" "$mail_string" <"$output"; then
       printf '%s\n' "*** Error: failed to send $script_name email."
       printf '%s\n' "The output file is $output"
     fi
   fi
 }
 
-
 # PARSE ARGUMENTS
 # --------------------------------------------------------------------
 while [ "$#" -gt 0 ]; do
   case "$1" in
-    --check-files)
-      check_files=true
+  --check-files)
+    check_files=true
     ;;
-    --no-check-files)
-      check_files=false
+  --no-check-files)
+    check_files=false
     ;;
-    --check-dirs)
-      check_dirs=true
+  --check-dirs)
+    check_dirs=true
     ;;
-    --no-check-dirs)
-      check_dirs=false
+  --no-check-dirs)
+    check_dirs=false
     ;;
-    --dir=*)
-      dir="${1#*=}"
+  --dir=*)
+    dir="${1#*=}"
     ;;
-    --file-size=*)
-      file_size="${1#*=}"
+  --file-size=*)
+    file_size="${1#*=}"
     ;;
-    --dir-limit=*)
-      dir_limit="${1#*=}"
+  --dir-limit=*)
+    dir_limit="${1#*=}"
     ;;
-    --dir-depth=*)
-      dir_depth="${1#*=}"
+  --dir-depth=*)
+    dir_depth="${1#*=}"
     ;;
-    --output-dir=*)
-      output_dir="${1#*=}"
+  --output-dir=*)
+    output_dir="${1#*=}"
     ;;
-    --output-file=*)
-      output_file="${1#*=}"
+  --output-file=*)
+    output_file="${1#*=}"
     ;;
-    --file-sort=*)
-      file_sort="${1#*=}"
+  --file-sort=*)
+    file_sort="${1#*=}"
     ;;
-    --sort=*)
-      file_sort="${1#*=}"
+  --sort=*)
+    file_sort="${1#*=}"
     ;;
-    --email=*)
-      unset email
-      email_addresses="${1#*=}"
-      IFS=', ' read -r -a email <<< "$email_addresses"
+  --email=*)
+    unset email
+    email_addresses="${1#*=}"
+    IFS=', ' read -r -a email <<<"$email_addresses"
     ;;
-    --vardump)
-      print_vars
+  --vardump)
+    print_vars
     ;;
-    --help)
-      print_help
+  --help)
+    print_help
     ;;
-    --version)
-      print_version
+  --version)
+    print_version
     ;;
-    --license)
-      print_license
+  --license)
+    print_license
     ;;
-    *)
-      printf '%s\n' "***Error: invalid argument ($1)"
-      print_help
+  *)
+    printf '%s\n' "***Error: invalid argument ($1)"
+    print_help
     ;;
   esac
   shift
 done
 
-
 # DO STUFF
 # --------------------------------------------------------------------
-# Do the housekeeping and make sure there is something to do. If so 
+# Do the housekeeping and make sure there is something to do. If so
 # we need to create the output file:
 housekeeping
 validate_dir
