Fixed formatting errors

diff --git a/local/bin/gitscripts/git-effort b/local/bin/gitscripts/git-effort
--- a/local/bin/gitscripts/git-effort
+++ b/local/bin/gitscripts/git-effort
@@ -3,7 +3,7 @@
 # From https://github.com/tj/git-extras/blob/master/bin/git-effort
 
 git_extra_mktemp() {
-    mktemp -t "$(basename "$0")".XXXXXXX
+  mktemp -t "$(basename "$0")".XXXXXXX
 }
 
 tmp=$(git_extra_mktemp)
@@ -47,7 +47,7 @@ hide_cursor() {
 show_cursor_and_cleanup() {
   tputq cnorm
   tputq sgr0
-  rm "$tmp" > /dev/null 2>&1
+  rm "$tmp" >/dev/null 2>&1
   exit 0
 }
 
@@ -65,15 +65,24 @@ active_days() {
 
 color_for() {
   if [ "$to_tty" = true ]; then
-    if   [ $1 -gt 200 ]; then color="$(tputq setaf 1)$(tputq bold)"
-    elif [ $1 -gt 150 ]; then color="$(tputq setaf 1)"  # red
-    elif [ $1 -gt 125 ]; then color="$(tputq setaf 2)$(tputq bold)"
-    elif [ $1 -gt 100 ]; then color="$(tputq setaf 2)"  # green
-    elif [ $1 -gt 75 ]; then color="$(tputq setaf 5)$(tputq bold)"
-    elif [ $1 -gt 50 ]; then color="$(tputq setaf 5)"  # purplish
-    elif [ $1 -gt 25 ]; then color="$(tputq setaf 3)$(tputq bold)"
-    elif [ $1 -gt 10 ]; then color="$(tputq setaf 3)"  # yellow
-    else color="$(tputq sgr0)" # default color
+    if [ $1 -gt 200 ]; then
+      color="$(tputq setaf 1)$(tputq bold)"
+    elif [ $1 -gt 150 ]; then
+      color="$(tputq setaf 1)" # red
+    elif [ $1 -gt 125 ]; then
+      color="$(tputq setaf 2)$(tputq bold)"
+    elif [ $1 -gt 100 ]; then
+      color="$(tputq setaf 2)" # green
+    elif [ $1 -gt 75 ]; then
+      color="$(tputq setaf 5)$(tputq bold)"
+    elif [ $1 -gt 50 ]; then
+      color="$(tputq setaf 5)" # purplish
+    elif [ $1 -gt 25 ]; then
+      color="$(tputq setaf 3)$(tputq bold)"
+    elif [ $1 -gt 10 ]; then
+      color="$(tputq setaf 3)" # yellow
+    else
+      color="$(tputq sgr0)" # default color
     fi
   else
     color=""
@@ -85,43 +94,43 @@ color_for() {
 #
 
 effort() {
-    path=$1
-    local commit_dates
-    local color reset_color commits len dot f_dot i msg active
-    reset_color=""
-    test "$to_tty" = true && reset_color="$(tputq sgr0)"
-    commit_dates=`dates "$path"`
-    [ $? -gt 0 ] && exit 255
+  path=$1
+  local commit_dates
+  local color reset_color commits len dot f_dot i msg active
+  reset_color=""
+  test "$to_tty" = true && reset_color="$(tputq sgr0)"
+  commit_dates=$(dates "$path")
+  [ $? -gt 0 ] && exit 255
 
-    # Ensure it's not just an empty line
-    if [ -z "`head -c 1 <<<$(echo $commit_dates)`" ]
-    then
-      exit 0
-    fi
+  # Ensure it's not just an empty line
+  if [ -z "$(head -c 1 <<<$(echo $commit_dates))" ]; then
+    exit 0
+  fi
 
-    commits=`wc -l <<<"$(echo "$commit_dates")"`
-    color='90'
+  commits=$(wc -l <<<"$(echo "$commit_dates")")
+  color='90'
 
-    # ignore <= --above
-    test $commits -le $above && exit 0
+  # ignore <= --above
+  test $commits -le $above && exit 0
 
-    # commits
-    color_for $(( $commits - $above ))
-    len=${#path}
-    dot="."
-    f_dot="$path"
-    i=0 ; while test $i -lt $(( $columns - $len )) ; do
-      f_dot=$f_dot$dot
-      i=$(($i+1))
-    done
+  # commits
+  color_for $(($commits - $above))
+  len=${#path}
+  dot="."
+  f_dot="$path"
+  i=0
+  while test $i -lt $(($columns - $len)); do
+    f_dot=$f_dot$dot
+    i=$(($i + 1))
+  done
 
-    msg=$(printf "  ${color}%s %-10d" "$f_dot" $commits)
+  msg=$(printf "  ${color}%s %-10d" "$f_dot" $commits)
 
-    # active days
-    active=`active_days "$commit_dates"`
-    color_for $(( $active - $above ))
-    msg="$msg $(printf "${color} %d${reset_color}\n" $active)"
-    echo "$msg"
+  # active days
+  active=$(active_days "$commit_dates")
+  color_for $(($active - $above))
+  msg="$msg $(printf "${color} %d${reset_color}\n" $active)"
+  echo "$msg"
 }
 
 #
@@ -142,39 +151,39 @@ sort_effort() {
   clear
   echo " "
   heading
-  < $tmp sort -rn -k 2
+  sort <$tmp -rn -k 2
 }
 
 declare -a paths=()
-while [ "${#}" -ge 1 ] ; do
+while [ "${#}" -ge 1 ]; do
 
   case "$1" in
-    --above)
-      shift
-      above=$1
-      ;;
-    --)
-      shift
-      args_to_git_log=$(printf " %q" "${@:1}")
-      break
-      ;;
-    --*)
-      usage
-      echo 1>&2 "error: unknown argument $1"
-      echo 1>&2 "error: if that argument was meant for git-log,"
-      echo 1>&2 "error: please put it after two dashes ( -- )."
-      exit 1
-      ;;
-    *)
-      paths+=( "$1" )
-      ;;
+  --above)
+    shift
+    above=$1
+    ;;
+  --)
+    shift
+    args_to_git_log=$(printf " %q" "${@:1}")
+    break
+    ;;
+  --*)
+    usage
+    echo 1>&2 "error: unknown argument $1"
+    echo 1>&2 "error: if that argument was meant for git-log,"
+    echo 1>&2 "error: please put it after two dashes ( -- )."
+    exit 1
+    ;;
+  *)
+    paths+=("$1")
+    ;;
   esac
 
   shift
 done
 
 # Exit if above-value is not an int
-if [ -z "${above##*[!0-9]*}" ] ; then
+if [ -z "${above##*[!0-9]*}" ]; then
   echo "error: argument to --above was not an integer" 1>&2
   exit 1
 fi
@@ -184,15 +193,15 @@ args_to_git_log="${args_to_git_log#\ \'\'}"
 export args_to_git_log
 
 # set column width to match longest filename
-columns=$(( $(git ls-files | awk '{ print length }' | sort -rn | head -1 ) + 5 ))
+columns=$(($(git ls-files | awk '{ print length }' | sort -rn | head -1) + 5))
 export columns
 
 # [path ...]
 
 if test "${#paths}" -eq 0; then
   save_ifs=$IFS
-  IFS=`echo -en "\n\b"`
-  paths=(`git ls-files`)
+  IFS=$(echo -en "\n\b")
+  paths=($(git ls-files))
   IFS=$save_ifs
   unset save_ifs
 fi
@@ -212,12 +221,11 @@ export to_tty
 export above
 export log_args
 
-
 bash_params=
 # If bash exits successfully with --import-functions,
 # then we need to pass it (FreeBSD probably)
 bash --import-functions -c ":" 1>/dev/null 2>&1
-if [ $? -eq 0 ] ; then
+if [ $? -eq 0 ]; then
   bash_params="--import-functions"
 fi
 
